# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horde < Formula
  desc "Cloud launcher for orc workflows"
  homepage "https://github.com/jorge-barreto/horde"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.8.0/horde_0.8.0_darwin_amd64.tar.gz"
      sha256 "b4b004c0e146e59fe11cc05edef0cd40e2265d235072e60c6c242f241373482c"

      def install
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.8.0/horde_0.8.0_darwin_arm64.tar.gz"
      sha256 "e3cb5420bc51353eb2d755a38d88129dddaabaff51312827af94b008429a0b02"

      def install
        bin.install "horde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.8.0/horde_0.8.0_linux_amd64.tar.gz"
      sha256 "3008b9bf850410f88cfd3125559efce1118f5e0d4e9f8a51db636d21dba14a8c"
      def install
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.8.0/horde_0.8.0_linux_arm64.tar.gz"
      sha256 "4bb134705b20b74dfd93d8198883ce67dee0a2ff640aff25db12e38910949590"
      def install
        bin.install "horde"
      end
    end
  end

  test do
    system "#{bin}/horde", "--version"
  end
end
