# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horde < Formula
  desc "Cloud launcher for orc workflows"
  homepage "https://github.com/jorge-barreto/horde"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.4.0/horde_0.4.0_darwin_amd64.tar.gz"
      sha256 "a7a7628aecdcd9079ae6e79b8db0a5ffe9edd403f03b237a13fee166244b7c4c"

      def install
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.4.0/horde_0.4.0_darwin_arm64.tar.gz"
      sha256 "987df4604df105f3301db3582227c37d2ed692b67f80e2167ca8363fc01ca9df"

      def install
        bin.install "horde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.4.0/horde_0.4.0_linux_amd64.tar.gz"
      sha256 "3828fc8442d2920571d1e2b623883c791371ac484ca8dc8c4d79bfe0b3139435"
      def install
        bin.install "horde"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/horde/releases/download/v0.4.0/horde_0.4.0_linux_arm64.tar.gz"
      sha256 "8b451c45d0aa85cfe949441541703ff5fe4286d24649ce19d0cb1a99c3decad1"
      def install
        bin.install "horde"
      end
    end
  end

  test do
    system "#{bin}/horde", "--version"
  end
end
