# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orc < Formula
  desc "Deterministic agent orchestrator"
  homepage "https://github.com/jorge-barreto/orc"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.1/orc_0.1.1_darwin_amd64.tar.gz"
      sha256 "9e2a9f5966405870d3bd6ce55a958c3d0f9bc8150d3e53bcc87e5339bb88c4d4"

      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.1/orc_0.1.1_darwin_arm64.tar.gz"
      sha256 "8d7121db51e4e79a28a1ae3253d0c470a8e955172a62a4b0d8dc2c7337c861d5"

      def install
        bin.install "orc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.1/orc_0.1.1_linux_amd64.tar.gz"
      sha256 "1f7d0acfc14efa4bf4149b6d91c9cc510746ce2c12fe511c4685b2430091c26a"
      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.1/orc_0.1.1_linux_arm64.tar.gz"
      sha256 "c8a583f1ddec199eb40bd3d9a25102cefd95cad4d0ffc67abfd895765f5e246b"
      def install
        bin.install "orc"
      end
    end
  end

  test do
    system "#{bin}/orc", "--version"
  end
end
