# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orc < Formula
  desc "Deterministic agent orchestrator"
  homepage "https://github.com/jorge-barreto/orc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.2/orc_0.1.2_darwin_amd64.tar.gz"
      sha256 "6e4399f15c2f1af49c2e304bfe3758baff4b3ad0ac4e7074d359ea5f5479547a"

      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.2/orc_0.1.2_darwin_arm64.tar.gz"
      sha256 "11f97cbc94db1c3336b171e2c2e803e61001cad00b7a3c63baf255375c4a4537"

      def install
        bin.install "orc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.2/orc_0.1.2_linux_amd64.tar.gz"
      sha256 "5f2680a2623aa9831cea19bf89d3bcaafd48ac8fe4e65994473048a9ed41ba23"
      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.1.2/orc_0.1.2_linux_arm64.tar.gz"
      sha256 "d46137732415fca9924c7e15e1889f57a7c4d559cce9d937f0698f5b739e1ab8"
      def install
        bin.install "orc"
      end
    end
  end

  test do
    system "#{bin}/orc", "--version"
  end
end
