# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orc < Formula
  desc "Deterministic agent orchestrator"
  homepage "https://github.com/jorge-barreto/orc"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.3.0/orc_0.3.0_darwin_amd64.tar.gz"
      sha256 "7ee08709edd50dc26112aca83a43da26062b13cea97bd5aeb31e379ef1856bc7"

      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.3.0/orc_0.3.0_darwin_arm64.tar.gz"
      sha256 "68b809c15ad7ca93ef706d44ee5f1fe6d4e95356d80962593acc293b588669d5"

      def install
        bin.install "orc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.3.0/orc_0.3.0_linux_amd64.tar.gz"
      sha256 "31f892d1cfec4e55297a06c498c94675407ac704fa8eeafa3447f071497ba777"
      def install
        bin.install "orc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorge-barreto/orc/releases/download/v0.3.0/orc_0.3.0_linux_arm64.tar.gz"
      sha256 "eae4ac033955b785ab0153c7a11a07581b49129f5e8cda88d7f42c4e6b7f1e9a"
      def install
        bin.install "orc"
      end
    end
  end

  test do
    system "#{bin}/orc", "--version"
  end
end
